apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  NODE_ENV: "production"
  FLASK_ENV: "production"
  JWT_EXPIRES_IN: "7d"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  # Service URLs
  AUTH_SERVICE_URL: "http://auth-service:3001"
  PRODUCT_SERVICE_URL: "http://product-service:3002"
  CART_SERVICE_URL: "http://cart-service:3003"
  ORDER_SERVICE_URL: "http://order-service:3004"
  ML_SERVICE_URL: "http://ml-service:3005"
  # Database URLs
  MONGODB_URI_AUTH: "mongodb://admin:$(MONGODB_PASSWORD)@mongodb:27017/ecommerce_auth?authSource=admin"
  MONGODB_URI_PRODUCTS: "mongodb://admin:$(MONGODB_PASSWORD)@mongodb:27017/ecommerce_products?authSource=admin"
  MONGODB_URI_ORDERS: "mongodb://admin:$(MONGODB_PASSWORD)@mongodb:27017/ecommerce_orders?authSource=admin"
  MONGODB_URI_ML: "mongodb://admin:$(MONGODB_PASSWORD)@mongodb:27017/ecommerce_ml?authSource=admin"
  REDIS_URL: "redis://redis:6379"