apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
      - name: ml-service
        image: ecommerce/ml-service:latest
        ports:
        - containerPort: 3005
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: FLASK_ENV
        - name: PORT
          value: "3005"
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: MONGODB_URI_ML
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: MONGODB_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: ecommerce
spec:
  selector:
    app: ml-service
  ports:
  - port: 3005
    targetPort: 3005
  type: ClusterIP