apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleQ== # your-jwt-secret-key
  MONGODB_PASSWORD: cGFzc3dvcmQ= # password
  EMAIL_USER: eW91ci1lbWFpbEBnbWFpbC5jb20= # your-email@gmail.com
  EMAIL_PASS: eW91ci1hcHAtcGFzc3dvcmQ= # your-app-password